import type { LatexSymbol } from '../symbol';

export const greekSymbols: LatexSymbol[] = [
  { symbol: 'A', latexSymbol: 'A', altText: 'Alpha (Uppercase)' },
  { symbol: 'α', latexSymbol: '\\alpha', altText: 'Alpha (Lowercase)' },
  { symbol: 'B', latexSymbol: 'B', altText: 'Beta (Uppercase)' },
  { symbol: 'β', latexSymbol: '\\beta', altText: 'Beta (Lowercase)' },
  { symbol: 'Γ', latexSymbol: '\\Gamma', altText: 'Gamme (Uppercase)' },
  { symbol: 'γ', latexSymbol: '\\gamma', altText: 'Gamme (Lowercase)' },
  { symbol: 'Δ', latexSymbol: '\\Delta', altText: 'Delta (Uppercase)' },
  { symbol: 'δ', latexSymbol: '\\delta', altText: 'Delta (Lowercase)' },
  { symbol: 'E', latexSymbol: 'E', altText: 'Epsilon (Uppercase)' },
  { symbol: 'ε', latexSymbol: '\\epsilon', altText: 'Epsilon (Lowercase)' },
  { symbol: 'Z', latexSymbol: 'Z', altText: 'Zeta (Uppercase)' },
  { symbol: 'ζ', latexSymbol: '\\zeta', altText: 'Zeta (Lowercase)' },
  { symbol: 'H', latexSymbol: 'H', altText: 'Eta (Uppercase)' },
  { symbol: 'η', latexSymbol: '\\eta', altText: 'Eta (Lowercase)' },
  { symbol: 'Θ', latexSymbol: '\\Theta', altText: 'Theta (Uppercase)' },
  { symbol: 'θ', latexSymbol: '\\theta', altText: 'Theta (Lowercase)' },
  { symbol: 'I', latexSymbol: 'I', altText: 'Iota (Uppercase)' },
  { symbol: 'ι', latexSymbol: '\\iota', altText: 'Iota (Lowercase)' },
  { symbol: 'K', latexSymbol: 'K', altText: 'Kappa (Uppercase)' },
  { symbol: 'κ', latexSymbol: '\\kappa', altText: 'Kappa (Lowercase)' },
  { symbol: 'Λ', latexSymbol: '\\Lambda', altText: 'Lambda (Uppercase)' },
  { symbol: 'λ', latexSymbol: '\\lambda', altText: 'Lambda (Lowercase)' },
  { symbol: 'M', latexSymbol: 'M', altText: 'Mu (Uppercase)' },
  { symbol: 'μ', latexSymbol: '\\mu', altText: 'Mu (Lowercase)' },
  { symbol: 'N', latexSymbol: 'N', altText: 'Nu (Uppercase)' },
  { symbol: 'ν', latexSymbol: '\\nu', altText: 'Nu (Lowercase)' },
  { symbol: 'Ξ', latexSymbol: '\\Xi', altText: 'Xi (Uppercase)' },
  { symbol: 'ξ', latexSymbol: '\\xi', altText: 'Xi (Lowercase)' },
  { symbol: 'O', latexSymbol: 'O', altText: 'Omicron (Uppercase)' },
  { symbol: 'o', latexSymbol: 'o', altText: 'Omicron (Lowercase)' },
  { symbol: 'Π', latexSymbol: '\\Pi', altText: 'Pi (Uppercase)' },
  { symbol: 'π', latexSymbol: '\\pi', altText: 'Pi (Lowercase)' },
  { symbol: 'P', latexSymbol: 'P', altText: 'Rho (Uppercase)' },
  { symbol: 'ρ', latexSymbol: '\\rho', altText: 'Rho (Lowercase)' },
  { symbol: 'Σ', latexSymbol: '\\Sigma', altText: 'Sigma (Uppercase)' },
  { symbol: 'σ', latexSymbol: '\\sigma', altText: 'Sigma (Lowercase)' },
  { symbol: 'T', latexSymbol: 'T', altText: 'Tau (Uppercase)' },
  { symbol: 'τ', latexSymbol: '\\tau', altText: 'Tau (Lowercase)' },
  { symbol: 'Y', latexSymbol: '\\Upsilon', altText: 'Upsilon (Uppercase)' },
  { symbol: 'υ', latexSymbol: '\\upsilon', altText: 'Upsilon (Lowercase)' },
  { symbol: 'Φ', latexSymbol: '\\Phi', altText: 'Phi (Uppercase)' },
  { symbol: 'φ', latexSymbol: '\\phi', altText: 'Phi (Lowercase)' },
  { symbol: 'X', latexSymbol: 'X', altText: 'Chi (Uppercase)' },
  { symbol: 'χ', latexSymbol: '\\chi', altText: 'Chi (Lowercase)' },
  { symbol: 'Ψ', latexSymbol: '\\Psi', altText: 'Psi (Uppercase)' },
  { symbol: 'ψ', latexSymbol: '\\psi', altText: 'Psi (Lowercase)' },
  { symbol: 'Ω', latexSymbol: '\\Omega', altText: 'Omega (Uppercase)' },
  { symbol: 'ω', latexSymbol: '\\omega', altText: 'Omega (Lowercase)' },
];

export const greekSymbolVariants: LatexSymbol[] = [
  { symbol: 'ϵ', latexSymbol: '\\varepsilon', altText: 'Variant epsilon' },
  { symbol: 'ϑ', latexSymbol: '\\vartheta', altText: 'Variant theta' },
  { symbol: 'ϰ', latexSymbol: '\\varkappa', altText: 'Variant kappa' },
  { symbol: 'ϖ', latexSymbol: '\\varpi', altText: 'Variant pi' },
  { symbol: 'ϱ', latexSymbol: '\\varrho', altText: 'Variant rho' },
  { symbol: 'ς', latexSymbol: '\\varsigma', altText: 'Final sigma' },
  { symbol: 'ϕ', latexSymbol: '\\varphi', altText: 'Variant phi' },
];
