services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=your_secure_password_here
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=latech'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  rabbitmq_data:
  postgres_data: