services:
  caddy:
    image: caddy:alpine
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - frontend
      - api
      - socket-server
    restart: unless-stopped

  frontend:
    image: ghcr.io/romanl1/latech/frontend:latest
    container_name: frontend
    environment:
      - VITE_API_HOST=https://latech.app/api
      - WEBSOCKET_SERVER_URL=wss://latech.app/ws
    restart: always

  renderer:
    image: ghcr.io/romanl1/latech/renderer:latest
    container_name: renderer
    environment:
      - 'PORT=8090'
      - 'RABBITMQ_HOST=rabbitmq'
      - 'RABBITMQ_PASSWORD=your_secure_password_here'
      - 'RABBITMQ_PORT=5672'
      - 'RABBITMQ_USERNAME=admin'
    restart: always

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-server
    ports:
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=your_secure_password_here
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  socket-server:
    image: ghcr.io/romanl1/latech/socket-server:latest
    container_name: socket-server
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    restart: always

  api:
    image: ghcr.io/romanl1/latech/api:latest
    container_name: api
    environment:
      - 'PORT=5001'
      - 'RABBITMQ_HOST=rabbitmq'
      - 'RABBITMQ_PASSWORD=your_secure_password_here'
      - 'RABBITMQ_PORT=5672'
      - 'RABBITMQ_USERNAME=admin'
      - 'RENDERER_URL=http://renderer:8090'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/latech'
      - 'FRONTEND_URL=https://latech.app'
    depends_on:
      - postgres
      - rabbitmq
    restart: always


  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=latech'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  rabbitmq_data:
  postgres_data:
  caddy_data:
  caddy_config: