spring.application.name=latech-renderer
spring.docker.compose.enabled=false
spring.grpc.server.port=9090
# Easily enable the reflection service for tools like grpcurl
spring.grpc.server.reflection.enabled=true