ALTER TABLE document ADD COLUMN last_change  TIMESTAMP WITH TIME ZONE;
ALTER TABLE document ADD COLUMN last_compile TIMESTAMP WITH TIME ZONE;
ALTER TABLE document ADD COLUMN pdf_path TEXT;
ALTER TABLE document ADD COLUMN compile_abandoned_at TIMESTAMP WITH TIME ZONE;