name: Pull Request Build

on:
  pull_request:
    branches:
      - main

jobs:
  # API application
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/api

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Setup Java and Gradle
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build and test the application
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build & test with Gradle
        run: ./gradlew build --no-daemon

  # Renderer application
  renderer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/renderer

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Setup Java and Gradle
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build and test the application
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build & test with Gradle
        run: ./gradlew build --no-daemon

  # Frontend application
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun ci

      - name: Lint with ESLint
        run: bun run lint:check
    
      - name: Lint with Prettier
        run: bun run prettier:check

      - name: Build
        run: bun run build:ci